/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ServerJ */

#ifndef _Included_ServerJ
#define _Included_ServerJ
#ifdef __cplusplus
extern "C" {
#endif
#undef ServerJ_PORT
#define ServerJ_PORT 8888L
/*
 * Class:     ServerJ
 * Method:    getUppercase
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerJ_getUppercase
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
